"""Le schéma de la base, par migrations numérotées : chaque migration s'applique une fois, dans une transaction, et
son numéro est noté dans schema_version. Pour faire évoluer le schéma, ajouter une migration à la fin (ne jamais
modifier une migration déjà livrée).

Les types s'écrivent avec des repères remplacés selon la base : {ID} (clé numérique automatique), {REF} (référence à
une clé), {BLOB} (octets), {REAL} (nombre à virgule), {BIG} (grand entier).
"""
from __future__ import annotations

TYPES = {
    "sqlite": {"ID": "INTEGER PRIMARY KEY", "REF": "INTEGER", "BLOB": "BLOB", "REAL": "REAL", "BIG": "INTEGER"},
    "postgres": {"ID": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "REF": "BIGINT", "BLOB": "BYTEA",
                 "REAL": "DOUBLE PRECISION", "BIG": "BIGINT"},
}

# Tables dans l'ordre de leurs dépendances (copie d'une base à l'autre), et celles qui ont une clé automatique.
TABLES = ("comptes", "espaces", "fichiers", "mains", "participants", "adversaires", "analyses", "reglages",
          "documents", "etudes", "entrainement", "revisions")
IDENTITY = ("comptes", "espaces", "fichiers", "mains", "entrainement")

MIGRATIONS: list[tuple[int, str, list[str]]] = [
    (1, "Comptes, espaces, historiques, mains, adversaires, analyses du solveur, réglages", [
        """CREATE TABLE comptes (
            id {ID},
            cle TEXT NOT NULL UNIQUE,          -- « local » sur ton ordinateur ; un client, en ligne
            nom TEXT NOT NULL,
            cree_le TEXT NOT NULL
        )""",
        """CREATE TABLE espaces (
            id {ID},
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            cle TEXT NOT NULL,                 -- « moi », ou « eleve:<identifiant> »
            nom TEXT NOT NULL,
            pseudo TEXT,                       -- son pseudo à la table (sinon détecté dans ses mains)
            cree_le TEXT NOT NULL,
            UNIQUE (compte_id, cle)
        )""",
        """CREATE TABLE fichiers (
            id {ID},
            espace_id {REF} NOT NULL REFERENCES espaces(id) ON DELETE CASCADE,
            nom TEXT NOT NULL,
            chemin TEXT,                       -- fichier du dossier des mains (NULL : importé dans l'application)
            taille {BIG},                      -- taille et date du fichier du dossier : inchangé, il n'est pas relu
            date_fichier {BIG},
            empreinte TEXT NOT NULL,           -- sha256 du texte
            contenu {BLOB} NOT NULL,           -- l'historique d'origine, compressé (zlib)
            mains INTEGER NOT NULL,
            importe_le TEXT NOT NULL,
            UNIQUE (espace_id, empreinte)
        )""",
        "CREATE INDEX fichiers_chemin ON fichiers (espace_id, chemin)",
        """CREATE TABLE mains (
            id {ID},
            espace_id {REF} NOT NULL REFERENCES espaces(id) ON DELETE CASCADE,
            fichier_id {REF} REFERENCES fichiers(id) ON DELETE SET NULL,
            site TEXT NOT NULL,
            numero TEXT NOT NULL,              -- numéro de la main sur le site
            joue_le TEXT NOT NULL,             -- date ISO
            format TEXT NOT NULL,              -- HU, 3-max, 6-max…
            sb {REAL} NOT NULL,
            bb {REAL} NOT NULL,
            lecture TEXT NOT NULL,             -- empreinte du code de lecture qui a produit « donnees »
            donnees {BLOB} NOT NULL,           -- la main lue, JSON compressé (models.hand_to_dict)
            UNIQUE (espace_id, site, numero)
        )""",
        "CREATE INDEX mains_date ON mains (espace_id, joue_le)",
        "CREATE INDEX mains_fichier ON mains (fichier_id)",
        """CREATE TABLE participants (
            main_id {REF} NOT NULL REFERENCES mains(id) ON DELETE CASCADE,
            joueur TEXT NOT NULL,
            position TEXT NOT NULL,
            net {REAL} NOT NULL,               -- gain de la main, en monnaie
            cartes TEXT,                       -- « AhKd » quand elles sont connues
            PRIMARY KEY (main_id, joueur)
        )""",
        "CREATE INDEX participants_joueur ON participants (joueur)",
        """CREATE TABLE adversaires (
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            nom TEXT NOT NULL,
            type TEXT NOT NULL,                -- reg | rec : choisi à la main (sinon suggéré d'après ses stats)
            maj_le TEXT NOT NULL,
            PRIMARY KEY (compte_id, nom)
        )""",
        """CREATE TABLE analyses (
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            cle TEXT NOT NULL,                 -- clé du spot de la main (postflop.study_key)
            main TEXT NOT NULL,                -- numéro de la main
            donnees {BLOB} NOT NULL,           -- résumé de la main face au solveur (theory/review.py), JSON compressé
            maj_le TEXT NOT NULL,
            PRIMARY KEY (compte_id, cle)
        )""",
        "CREATE INDEX analyses_main ON analyses (compte_id, main)",
        """CREATE TABLE reglages (
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            cle TEXT NOT NULL,
            valeur TEXT NOT NULL,              -- JSON
            PRIMARY KEY (compte_id, cle)
        )""",
    ]),
    (2, "Documents du solveur (tailles, plans, résolutions, ranges…), études, journal de l'entraîneur, révisions", [
        """CREATE TABLE documents (
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            type TEXT NOT NULL,                -- tailles, plan, resolution, precision, ranges… (db/documents.py)
            cle TEXT NOT NULL,
            donnees {BLOB} NOT NULL,           -- JSON compressé (zlib)
            maj_le TEXT NOT NULL,
            PRIMARY KEY (compte_id, type, cle)
        )""",
        """CREATE TABLE etudes (
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            cle TEXT NOT NULL,                 -- clé de l'étude (postflop.study_key) ; l'arbre : fichier <cle>.etude
            type TEXT NOT NULL,                -- hand | spot | spot-ajuste
            fiche {BLOB} NOT NULL,             -- la fiche de l'étude, JSON compressé
            taille {BIG} NOT NULL,             -- octets du fichier de l'arbre
            maj_le TEXT NOT NULL,
            PRIMARY KEY (compte_id, cle)
        )""",
        """CREATE TABLE entrainement (
            id {ID},
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            le {BIG} NOT NULL,                 -- moment de la décision (secondes depuis 1970)
            donnees TEXT NOT NULL              -- la décision jugée, JSON (app/trainer.py)
        )""",
        "CREATE INDEX entrainement_compte ON entrainement (compte_id, le)",
        """CREATE TABLE revisions (
            compte_id {REF} NOT NULL REFERENCES comptes(id) ON DELETE CASCADE,
            type TEXT NOT NULL,                -- un type de document, « etudes », « reglages »…
            numero {BIG} NOT NULL,             -- change à chaque écriture : les calculs qui en dépendent se refont
            PRIMARY KEY (compte_id, type)
        )""",
    ]),
]


def ddl(statement: str, dialect: str) -> str:
    out = statement
    for token, sql in TYPES[dialect].items():
        out = out.replace("{" + token + "}", sql)
    return out


def version(db) -> int:
    return db.value("SELECT MAX(version) FROM schema_version", default=0)


def migrate(db) -> int:
    """Applique les migrations qui manquent ; renvoie la version du schéma."""
    db.execute("CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY, description TEXT NOT NULL, "
               "applique_le TEXT NOT NULL)")
    from . import now
    current = version(db)
    for number, description, statements in MIGRATIONS:
        if number <= current:
            continue
        with db.transaction():
            if version(db) >= number:  # appliquée entre-temps par un autre processus
                continue
            for statement in statements:
                db.execute(ddl(statement, db.dialect))
            db.execute("INSERT INTO schema_version (version, description, applique_le) VALUES (?, ?, ?)",
                       (number, description, now()))
    return version(db)
